import os
import json
from datetime import datetime
from typing import Dict
from weasyprint import HTML
import tempfile

def generate_pdf_report(report_data: Dict, scan_id: int) -> str:
    """Генерация PDF отчета"""
    
    # Создаем HTML контент
    html_content = generate_html_content(report_data, scan_id)
    
    # Создаем временный файл
    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as f:
        pdf_path = f.name
    
    # Генерируем PDF
    HTML(string=html_content).write_pdf(pdf_path)
    
    return pdf_path

def generate_html_report(report_data: Dict, scan_id: int) -> str:
    """Генерация HTML отчета"""
    
    html_content = generate_html_content(report_data, scan_id)
    
    # Создаем временный файл
    with tempfile.NamedTemporaryFile(suffix='.html', delete=False, mode='w', encoding='utf-8') as f:
        f.write(html_content)
        html_path = f.name
    
    return html_path

def generate_html_content(report_data: Dict, scan_id: int) -> str:
    """Генерация HTML контента для отчета"""
    
    exec_summary = report_data['executive_summary']
    detailed_findings = report_data['detailed_findings']
    
    # Простой HTML шаблон
    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Security Report - Scan #{scan_id}</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; }}
            .header {{ background: #2c3e50; color: white; padding: 20px; border-radius: 5px; }}
            .section {{ margin: 20px 0; padding: 15px; border: 1px solid #ddd; border-radius: 5px; }}
            .critical {{ color: #e74c3c; font-weight: bold; }}
            .high {{ color: #e67e22; }}
            .medium {{ color: #f39c12; }}
            .low {{ color: #3498db; }}
            .info {{ color: #27ae60; }}
            table {{ width: 100%; border-collapse: collapse; }}
            th, td {{ padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }}
            th {{ background-color: #f2f2f2; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>VulnScout Security Assessment Report</h1>
            <p>Scan ID: {scan_id} | Target: {report_data['report_metadata']['target']} | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
        </div>
        
        <div class="section">
            <h2>Executive Summary</h2>
            <p><strong>Total Hosts Scanned:</strong> {exec_summary['total_hosts_scanned']}</p>
            <p><strong>Total Vulnerabilities Found:</strong> {exec_summary['total_vulnerabilities_found']}</p>
            <p><strong>Overall Risk Score:</strong> {exec_summary['overall_risk_score']:.1f}/10.0</p>
            
            <h3>Vulnerability Distribution</h3>
            <table>
                <tr><th>Severity</th><th>Count</th></tr>
                {"".join(f"<tr><td class='{sev}'>{sev}</td><td>{count}</td></tr>" for sev, count in exec_summary['vulnerability_distribution'].items())}
            </table>
        </div>
        
        <div class="section">
            <h2>Top Critical Vulnerabilities</h2>
            <table>
                <tr><th>Vulnerability</th><th>CVSS Score</th><th>Host</th><th>Port</th></tr>
                {"".join(f"<tr><td>{vuln['title']}</td><td>{vuln.get('cvss_score', 'N/A')}</td><td>{vuln['host']}</td><td>{vuln.get('port', 'N/A')}</td></tr>" for vuln in exec_summary.get('top_critical_vulnerabilities', []))}
            </table>
        </div>
        
        <div class="section">
            <h2>Detailed Findings</h2>
            <h3>Hosts</h3>
            {"".join(f"<h4>{host['ip_address']} ({host.get('hostname', 'N/A')})</h4><ul>{"".join(f"<li>Port {port['port']}: {port['service']} {port.get('version', '')}</li>" for port in host.get('open_ports', []))}</ul>" for host in detailed_findings.get('hosts', []))}
            
            <h3>Vulnerabilities</h3>
            <table>
                <tr><th>Title</th><th>Severity</th><th>CVSS</th><th>Host:Port</th></tr>
                {"".join(f"<tr><td>{vuln['title']}</td><td class='{vuln['severity']}'>{vuln['severity']}</td><td>{vuln.get('cvss_score', 'N/A')}</td><td>{vuln['host']}:{vuln.get('port', 'N/A')}</td></tr>" for vuln in detailed_findings.get('vulnerabilities', []))}
            </table>
        </div>
        
        <div class="section">
            <h2>Recommendations</h2>
            <ol>
                {"".join(f"<li><strong>{rec['vulnerability_type']}</strong> (Priority: {rec['priority']}): {rec['recommendation']}</li>" for rec in report_data.get('recommendations', []))}
            </ol>
        </div>
        
        <div class="section">
            <p><em>Report generated by VulnScout Platform</em></p>
        </div>
    </body>
    </html>
    """
    
    return html_template

def save_json_report(report_data: Dict, scan_id: int) -> str:
    """Сохранение отчета в JSON файл"""
    
    reports_dir = "reports"
    os.makedirs(reports_dir, exist_ok=True)
    
    filename = f"scan_{scan_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    filepath = os.path.join(reports_dir, filename)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(report_data, f, indent=2, ensure_ascii=False)
    
    return filepath